#!/bin/sh
# Copyright (c) 2024, Julien Seguinot (juseg.dev)
# GNU General Public License v3.0+ (https://www.gnu.org/licenses/gpl-3.0.txt)
#
# gruvbox-light - switch to gruvbox-light on-the-fly
#
# After:
# - https://unix.stackexchange.com/questions/232881/
# - https://github.com/morhetz/gruvbox-generalized

# allow custom contrast
case $* in
    -h|--hard) bg=#f9f5d7 ; shift ;;
    -s|--soft) bg=#f2e5bc ; shift ;;
    *) bg=#f2e5bc ;;
esac

# change terminal colors
echo -en "\033]11;[85]${bg}\007"
echo -en '\033]10;#3c3836\007'
echo -en '\033]4;0#fdf4c1\007'
echo -en '\033]4;8#928374\007'
echo -en '\033]4;1#cc241d\007'
echo -en '\033]4;9#9d0006\007'
echo -en '\033]4;2#98971a\007'
echo -en '\033]4;10#79740e\007'
echo -en '\033]4;3#d79921\007'
echo -en '\033]4;11#b57614\007'
echo -en '\033]4;4#458588\007'
echo -en '\033]4;12#076678\007'
echo -en '\033]4;5#b16286\007'
echo -en '\033]4;13#8f3f71\007'
echo -en '\033]4;6#689d6a\007'
echo -en '\033]4;14#427b58\007'
echo -en '\033]4;7#7c6f64\007'
echo -en '\033]4;15#3c3836\007'
