#!/bin/sh
# Copyright (c) 2022, Julien Seguinot (juseg.github.io)
# GNU General Public License v3.0+ (https://www.gnu.org/licenses/gpl-3.0.txt)
#
# X11 profile (sourced by e.g. /etc/lightdm/Xsession)

# xdg base directory
export XDG_CONFIG_HOME=$HOME/.config

# source shell profile (needed by lightdm)
source $XDG_CONFIG_HOME/shell/profile

# load X resources
xrdb -merge $XDG_CONFIG_HOME/x11/xresources
