#!/bin/sh
# Copyright (c) 2022, Julien Seguinot (juseg.github.io)
# GNU General Public License v3.0+ (https://www.gnu.org/licenses/gpl-3.0.txt)
#
# X11 profile (sourced by e.g. /etc/lightdm/Xsession)

# load X resources
xrdb -merge $XDG_CONFIG_HOME/x11/xresources
