#!/bin/sh
# Copyright (c) 2022-2024, Julien Seguinot (juseg.dev)
# GNU General Public License v3.0+ (https://www.gnu.org/licenses/gpl-3.0.txt)
#
# X11 profile (sourced by e.g. /etc/lightdm/Xsession)
#
# FIXME: these environment variables are read when starting an X session, so
# they will be available in X-terminals, but not in consoles or remote shells.
# Also not in systemd services, this is an issue for e.g. GPG!
# I want to make them accessible to fish, but fish uses a different syntax.
# Here are possible solutions:
# - rewrite this file as `setenv ENV value` and implement a setenv function in
#   bash (export VAR=value) and a setenv function in fish (set -g ENV value).
# - remove lightdm, and fire X from fish (my preferred solution for now).

# favourite programs
export BROWSER=/usr/bin/firefox
export EDITOR=/usr/bin/nvim
export PAGER=/usr/bin/less

# expand path
export PATH=$HOME/.config/scripts:$PATH
export PATH=$HOME/.local/share/gem/ruby/2.7.0/bin:$PATH
export PATH=$HOME/git/code/dotfiles/bin:$PATH
export PATH=$HOME/git/code/sentinelflow:$PATH

# local python modules
export PYTHONPATH=""
export PYTHONPATH=$HOME/git/code/absplots:$PYTHONPATH
export PYTHONPATH=$HOME/git/code/hyoga:$PYTHONPATH
export PYTHONPATH=$HOME/git/yard/cartowik:$PYTHONPATH

# xdg base directories
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"

# cache files and directories
export BUNDLE_USER_CACHE="$XDG_CACHE_HOME/bundle"
export ERRFILE="$XDG_CACHE_HOME/X11/xsession-errors"

# config files and directories
# (gtk2 is used by epdfview, lxappearance, viewnior)
# (epdfview is discontinued, should consider evince or mupdf)
export BUNDLE_USER_CONFIG="$XDG_CONFIG_HOME/bundle"
export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc-2.0"
export MBSYNCRC="$XDG_CONFIG_HOME/mbsync/config"
export NOTMUCH_CONFIG="$XDG_CONFIG_HOME/notmuch/config"
export WGETRC="$XDG_CONFIG_HOME/wgetrc"

# data files and directories
export BUNDLE_USER_HOME="$XDG_DATA_HOME/bundle"
export GNUPGHOME="$XDG_DATA_HOME/gnupg"
export HISTFILE="$XDG_DATA_HOME/history"
export IPYTHONDIR="$XDG_DATA_HOME/ipython"
export PASSWORD_STORE_DIR="$XDG_DATA_HOME/password-store"
export TEXMFHOME="$XDG_DATA_HOME/texmf"

# runtime sockets
# (https://wiki.archlinux.org/title/SSH_keys#Start_ssh-agent_with_systemd_user)
export RXVT_SOCKET="$XDG_RUNTIME_DIR/urxvt-socket"
export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"

# these directories can't be moved at all
# (see https://wiki.archlinux.org/title/XDG_Base_Directory)
# .mozilla (18-yr old bug https://bugzilla.mozilla.org/show_bug.cgi?id=259356)
# .thunderbird (11-yr bug https://bugzilla.mozilla.org/show_bug.cgi?id=735285)
# .ssh (won't fix https://bugzilla.mindrot.org/show_bug.cgi?id=2050)
# .Xauthority (export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority" breaks lightdm)
# .zoom (export SSB_HOME="$XDG_DATA_HOME"/zoom will break some features)

# application settings
export QT_QPA_PLATFORMTHEME="qt5ct"  # used by manjaro-settings-manager
export FZF_DEFAULT_OPTS="--layout=reverse --height 40%"  # drop-down style

# load X resources and adapt dpi to screen height
xrdb -merge $XDG_CONFIG_HOME/x11/xresources
height=$(xrandr -q|sed -n 's/.*current.* x \([0-9]*\),.*/\1/p')
echo "Xft.dpi: $((96*$height/1080))" | xrdb -merge
